version: "3"

services:
  parser_1:
    image: yazansh/namel:latest
    container_name: parser_1
    environment:
      - parser_name=parser_1
    networks:
      - kafka
    entrypoint: python run-parser.py

  parser_2:
    image: yazansh/namel:latest
    container_name: parser_2
    environment:
      - parser_name=parser_2
    networks:
      - kafka
    entrypoint: python run-parser.py

networks:
  kafka:
    external:
      name: distributed_crawler_2_kafka


