version: "3"

services:
  node_1:
    image: yazansh/namel:latest
    container_name: node_1
    environment:
      - node_name=node_1
    networks:
      - kafka
    entrypoint: python run-hybrid.py
  #    depends_on:
  #      - splash

  node_2:
    image: yazansh/namel:latest
    container_name: node_2
    environment:
      - node_name=node_2
    networks:
      - kafka
    entrypoint: python run-hybrid.py
  #    depends_on:
  #      - splash

#  scraper_1:
#    image: yazansh/namel:latest
#    container_name: node_1
#    environment:
#      - node_name=node_1
#    networks:
#      - kafka
#    entrypoint: python run-hybrid.py
#  #    depends_on:
#  #      - splash
#
#  scraper_2:
#    image: yazansh/namel:latest
#    container_name: scraper_2
#    environment:
#      - node_name=scraper_2
#    networks:
#      - kafka
#    entrypoint: python run-hybrid.py
#    depends_on:
#      - splash

#  splash:
#    image: scrapinghub/splash:latest
#    container_name: splash
#    ports:
#      - 8050:8050


networks:
  kafka:
    external:
      name: namel_kafka


